### PR TITLE
 Added instruction to create virtualenv for Windows & formatted README

### PR DESCRIPTION
**Pull request by hvrc**
Instruction to create virtualenv for Windows was missing, so I added that and also formatted the README

### CODE REVIEW

**Comment by makkoncept** [comment]
hi @hvrc , thanks for PR. Readme looks good but i think that the command for creating venv on windows and linux will be same, difference is in activating it. [Documentation](https://docs.python.org/3/tutorial/venv.html#creating-virtual-environments). I am not completely sure though. can you look into it

**Comment by hvrc** [comment]
You're right! The only issue was that I was getting an error saying "python3: command not found" for some reason, so I had to use "python -m venv venv". So I followed [this documentation](https://github.com/pallets/flask/tree/1.0.2/examples/tutorial#install) and the separate commands for Linux (python3) & Windows (py -3) worked safely. Maybe I have an issue with Python 3's path in my system

**Comment by makkoncept** [comment]
@hvrc , for the sake of consistency, can you change `py -3` to `python3` in windows section. Everything looks good,  i will then merge the PR.

**Comment by hvrc** [comment]
@makkoncept Done

**Pull request merged**
